version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - web_data:/var/lib/web_data

volumes:
  web_data:
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=8g"